---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secret
  namespace: app
spec:
  encryptedData:
    DB_PASSWORD: AgC405Hz4thjKdZP3QLuLwR5Na+1Whx2nXIMp7Ub0BC7t4rVNvS3HxKn7H3G04pm7GHYGQ5YPYnxpTFpgJ9wA5ZYcIe81X8fMBZMM/LOBcxWzKrUEtVxUE0kgO9jrHsKK4jajHHqMNKZ5eS8slykFel6fCT+eeaWf3ZZaSByqLYtSMvX3szxRFntg6QRdv0pSNr7ncRnM4Mt4gqD5rOPlL4GzZbZGr9nL5guKBs3QhxB1mfTg9I+Bdb8rvziZfZ1IEKQm7R6mqqJPFhrg+TCL+MAIu9Yj/t6SLha83BpFl9uWhD3Ukvl8vTlpCLl11R+Ax3D1SlnvVxHxJTHg9lTC7B+vwRJJU+TXxfo2ko2bdTZF9PeNxp6gEBXw1RsQOtLZIYmbYsKLpmVX0TndZYPZf61hr6RFY9AK4oQmqe8m6vQPexlBBXZZY5evby1pmSORRxQ16SblXFxxIMZ8j0Z0rCasXxEIstr9aD/mGpDnbgZMnB5qq3IOosOCLq8S9EhXimVdfsb8GhcOqFyn6xdjDSmtVk/lpjZ8FkiFY+d/wJ0xt1peA0qlv6zP5EXB4lW4RHWbRHkPMuF8r9iMvWZB1F4PxrI7Bh7iYdAmxOFWeU6YF4qvpByMVCOjfF6T8YkZU8GXFNSYzPa1iJ3etivXfAJ1ng6EFXFS+An6bLWPCsxf/2dQym+OOtenm4UBtHOEJAYLOTXKrZdBSc1Xw==
  template:
    metadata:
      creationTimestamp: null
      name: api-secret
      namespace: app
